-- Fire-danger (FWI) engine — Milestone 1 schema.
-- Pattern follows scripts/sql/whi-545-schema.sql (goes_*). RLS enabled,
-- anon/authenticated blocked; service_role bypasses (used by the function).
--
-- APPLY GATED: present this file and wait for explicit OK before running it
-- against the shared production project (qmzuwnilehldvobjsbcs). CREATE TABLE
-- only — additive, no destructive statements — but still gated per protocol.

create table if not exists public.danger_zones (
  id            text primary key,
  province      text not null,
  name          text not null,
  lat           double precision not null,
  lng           double precision not null,
  bbox          double precision[] not null,   -- [south, north, west, east]
  geometry      jsonb,                          -- nullable; painted polygons land in M2
  created_at    timestamptz not null default now()
);

create table if not exists public.fire_danger_state (
  zone_id   text not null references public.danger_zones(id) on delete cascade,
  date      date not null,
  ffmc      double precision not null,
  dmc       double precision not null,
  dc        double precision not null,
  primary key (zone_id, date)
);

create table if not exists public.fire_danger (
  id            bigint generated by default as identity primary key,
  zone_id       text not null references public.danger_zones(id) on delete cascade,
  computed_at   date not null,
  target_date   date not null,
  fwi           double precision not null,
  danger_class  text not null,
  isi           double precision,
  bui           double precision,
  temp          double precision,
  rh            double precision,
  wind          double precision,
  precip        double precision,
  unique (zone_id, computed_at, target_date)
);

create index if not exists fire_danger_zone_target_idx
  on public.fire_danger (zone_id, target_date);

alter table public.danger_zones      enable row level security;
alter table public.fire_danger_state enable row level security;
alter table public.fire_danger       enable row level security;
-- No policies -> anon/authenticated blocked; service_role bypasses RLS.
