"""Download CEMS FWI reanalysis (GRIB) for the TDF area and extract the two
points -> cems_tdf.csv. Uses the exact API request generated by the EWDS dataset
form (cems-fire-historical-v1, FWI + 3 moisture codes, 2014-2022). Run once.

Reference series to validate our Open-Meteo-based FWI against.
"""
import os
import cdsapi
import xarray as xr
import pandas as pd

POINTS = {"rio_grande": (-53.7878, -67.7091), "ushuaia": (-54.8019, -68.3029)}
OUT_GRIB = "cems_fwi.grib"

DATASET = "cems-fire-historical-v1"
REQUEST = {
    "product_type": "reanalysis",
    "variable": [
        "drought_code",
        "duff_moisture_code",
        "fine_fuel_moisture_code",
        "fire_weather_index",
    ],
    "dataset_type": "consolidated_dataset",
    "system_version": ["4_1"],
    "year": ["2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022"],
    "month": [f"{m:02d}" for m in range(1, 13)],
    "day": [f"{d:02d}" for d in range(1, 32)],
    "grid": "original_grid",
    "data_format": "grib",
    "area": [-52.5, -69, -55.2, -66],  # [North, West, South, East], covers both points
}


def download() -> None:
    if os.path.exists(OUT_GRIB):
        print(f"{OUT_GRIB} already exists ({os.path.getsize(OUT_GRIB)} bytes), skipping download")
        return
    c = cdsapi.Client()
    c.retrieve(DATASET, REQUEST).download(OUT_GRIB)
    print(f"downloaded {OUT_GRIB} ({os.path.getsize(OUT_GRIB)} bytes)")


def _open_fwi() -> "xr.DataArray":
    """Open the GRIB and return the FWI DataArray. The file has 4 variables; we
    only need the Fire Weather Index. cfgrib exposes them by shortName."""
    ds = xr.open_dataset(OUT_GRIB, engine="cfgrib", backend_kwargs={"indexpath": ""})
    print("data_vars:", list(ds.data_vars))
    for v in ds.data_vars:
        if "fwi" in v.lower() or "fire_weather" in v.lower():
            print("using FWI var:", v)
            return ds[v]
    raise SystemExit(f"FWI variable not found among {list(ds.data_vars)}")


def extract() -> None:
    fwi = _open_fwi()
    rows = []
    for name, (lat, lng) in POINTS.items():
        series = fwi.sel(latitude=lat, longitude=lng, method="nearest").to_series()
        for date, val in series.items():
            rows.append({
                "point": name,
                "date": pd.Timestamp(date).strftime("%Y-%m-%d"),
                "fwi_cems": float(val),
            })
    df = pd.DataFrame(rows).dropna(subset=["fwi_cems"])
    df.to_csv("cems_tdf.csv", index=False)
    print(f"wrote cems_tdf.csv: {len(df)} rows")


if __name__ == "__main__":
    download()
    extract()
